### ISSUE TITLE
rename in submodule pciutils the RELEASE file

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#100]
Please rename pciutils/blob/master/maint/RELEASE to RELEASE.TXT.
Reason: Two files with the same case insensitive name causes problems under Windows. 
pciutils is not from MEN but already modified for MDIS, so this non functional minor modifications shouldn't be a problem.

See https://github.com/MEN-Mikro-Elektronik/pciutils/blob/master/maint/RELEASE

**Comment by mlassota** [comment]
Fixed
