### ISSUE TITLE
Add support for GROUP_ID_x identifier in scan_system.sh script.

### ISSUE THREAD

**Issue by KonradJPE** [MEN-Mikro-Elektronik/13MD05-90#108]
Are the groups of IP cores still used in chameleon boards (GROUP_ID_x identifier)? 
For now it seems that scan_system.sh script does not support it, but mdiswiz does.
 

> Yes, it is still used and must be supported. However it is rarely used. E.g. the QSPI driver uses this feature for certain driver variants.

Additional information in document: 
[GROUP_ID_x.pdf](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/3127159/GROUP_ID_x.pdf)

**Comment by KonradJPE** [comment]
@dpfeuffer , @JSierl 
Is it possible to send us hardware that is using GROUP_ID identifier, so we could test and implement this feature into scan_system script?

**Comment by JSierl** [comment]
Please postpone this at the moment.
Actually, only the QSPI driver https://github.com/MEN-Mikro-Elektronik/13Z010-06 uses chameleon groups.

**Comment by dpfeuffer** [comment]
Just a remark: The 13Z062-06 DMA test driver also uses groups, but this driver is currently only available in MEN MCVS.

**Comment by dpfeuffer** [comment]
I close this issue, because GROUP_ID is currently not used from any MDIS driver of 13MD05-90_02_01.
