### ISSUE TITLE
HWBUG  tool no IO map support

### ISSUE THREAD

**Issue by AndreasGeissler** [MEN-Mikro-Elektronik/13MD05-90#109]
With the current configuration of HWBUG no IO mapped accesses are supported. The default program.mak file shall enable the switch:
MAC_IO_MAPPED_EN

Therefore add "-DMAC_IO_MAPPED_EN" to MAK_SWITCH
= MAK_SWITCH=-DLINUX -DMAC_IO_MAPPED_EN

**Comment by KonradJPE** [comment]
HWBUG tool should now compile without error/warnings with default configuration: 
MAK_SWITCH=-DLINUX -DMAC_IO_MAPPED_EN

Please refer to issue: https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/75
