### ISSUE TITLE
HWBUG tool move to own repository

### ISSUE THREAD

**Issue by AndreasGeissler** [MEN-Mikro-Elektronik/13MD05-90#110]
The HWBUG tool is currently part of the top repository 13MD05-90. It should be moved to it's own repository like the fpga_load tool:

For example create a repository with name "mdis_tools_hwbug"
and add it as submodule to 13MD05-90

**Comment by KonradJPE** [comment]
HWBUG moved to repository: 
https://github.com/MEN-Mikro-Elektronik/mdis_tools_hwbug
