### ISSUE TITLE
hwbug cleanup

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#118]
- R1. Rename repo *mdis_tools_hwbug* in *hwbug*
- R2. Rework makefiles (Makefile, rules_hwbug.mak, program.mak) to be able to build hwbug without any MDIS dependencies via make, as well as with the MDIS build environment.
- R3. Add a package description file (hwbug.xml) to be able to add the hwbug tool to the MDIS build from mdiswiz (Project -> Settings -> Software Modules). The hwbug sources shall fit into the MDIS source tree to be buildable.
- R4. Remove Lynx and HPRT support:
       - delete hprt.c, lynx.c
       - remove LYNX/HPRT switches in hwbug.h
- R5. Remove unnecessary file makefile.old
- R6. Rename hwbug binary to hwbug_ppc
- R7. Describe in README.md: Purpose and usage of hwbug, included hwbug binaries, how to build hwbug w/o MDIS

Please evaluate if fpga_load and mm_ident tool could also be build by selecting it in mdiswiz (Project -> Settings -> Software Modules).

**Comment by KonradJPE** [comment]
> R3. Add a package description file (hwbug.xml) to be able to add the hwbug tool to the MDIS build from mdiswiz (Project -> Settings -> Software Modules). The hwbug sources shall fit into the MDIS source tree to be buildable.

Is 'hwbug.xml' necessary? It seems that mdiswiz does not use .xml files for software modules at all. (Project -> Settings -> Software Modules). All software modules are hardcoded in mdiswiz sources (13Y008-90/COM/configuration.cpp)

**Comment by dpfeuffer** [comment]
You're right! I had forgotten that general MDIS tools are described in configuration.cpp. Thanks for your inquiry.

**Comment by KonradJPE** [comment]
> Please evaluate if fpga_load and mm_ident tool could also be build by selecting it in mdiswiz (Project -> Settings -> Software Modules).

It could be done for mm_ident tool.
When it comes to fpga_load it will require to add several additional user LIBs for build - it will be necessary to select manually several additional software modules by user, or develop new functions in mdis code that will select/unselect automatically all necessary libs. Is it necessary feature? 
If yes, then i would prefer to open separate issue for this, because it will require to add some major changes in mdiswiz.

**Comment by dpfeuffer** [comment]
>It could be done for mm_ident tool.

I see you did it already, thanks.

>When it comes to fpga_load it will require to add several additional user LIBs for build - it will be necessary to select manually several additional software modules by user

That would be ok for now and is better as no possibility at all to build fpga_load from mdiswiz. I could describe in the MDIS User Manual that additional libs are required. I assume the required libs are already present, so that the user can select it. Am I right? 
Would it be possible to note the necessary libs in the description of fpga_load so that the user see it within mdiswiz (Project -> Settings -> Software Modules)?

**Comment by KonradJPE** [comment]
> I assume the required libs are already present, so that the user can select it. Am I right?

Unfortunately they are not present in (Project -> Settings -> Software Modules) by default. Default libs are: 
```
ALL_USR_LIBS = \
	USR_OSS/library.mak \
	USR_UTL/COM/library.mak
```
fpga_load needs this lib set: 

```
ALL_USR_LIBS = \
     USR_OSS/library.mak \
     USR_UTL/COM/library.mak \
     OSS/library_usr.mak \
     DBG/library_usr.mak \
     CHAMELEON/COM/library_io.mak \
     CHAMELEON/COM/library_io_sw.mak \
     CHAMELEON/COM/library_usr.mak \
     CHAMELEON/COM/library_usr_io.mak \
     CHAMELEON/COM/library_usr_sw.mak \
     CHAMELEON/COM/library_usr_io_sw.mak \
     VME4L_API/library.mak

```

Morover 'pciutils' lib is required.

So to make it work, I have to add somehow all required libs into "Software Modules". I will also have to check what happens when this libs will be selected by user, and if the same libs will be added together with some board/module.
So it will take some time to succeed. Is this acceptable solution?

**Comment by dpfeuffer** [comment]
Due to the effort and uncertain success of compiling fpga_load from the MDIS wizard, we will not do this for the time being (for 13MD05-90_02_01).
If hwbug cleanup is complete, please close this issue.
If we need fpga_load compilation from MDIS wizard later, then we will create a new issue.

**Comment by KonradJPE** [comment]
Summary: 

> R1. Rename repo mdis_tools_hwbug in hwbug
> R2. Rework makefiles (Makefile, rules_hwbug.mak, program.mak) to be able to build hwbug without any MDIS dependencies via make, as well as with the MDIS build environment.
> R3. Add a package description file (hwbug.xml) to be able to add the hwbug tool to the MDIS build from mdiswiz (Project -> Settings -> Software Modules). The hwbug sources shall fit into the MDIS source tree to be buildable.
> R4. Remove Lynx and HPRT support:
>     - delete hprt.c, lynx.c
>     - remove LYNX/HPRT switches in hwbug.h
> R5. Remove unnecessary file makefile.old
> R6. Rename hwbug binary to hwbug_ppc
> R7. Describe in README.md: Purpose and usage of hwbug, included hwbug binaries, how to build hwbug w/o MDIS

Done

> Please evaluate if fpga_load and mm_ident tool could also be build by selecting it in mdiswiz (Project -> Settings -> Software Modules).

Done for mm_ident tool.
