### ISSUE TITLE
scan_system.sh does not find G022 board

### ISSUE THREAD

**Issue by xrombik** [MEN-Mikro-Elektronik/13MD05-90#127]
**MDISforLinux/scan_system.sh** does not have **G022** board code in `CPU_KNOWN_BOARDS` variable, so it is impossible to find this board with this script. This https://github.com/MEN-Mikro-Elektronik/13MD05-90/pull/129 fixes the issue

**Comment by KonradJPE** [comment]
Add **G022** board into scan_system.sh script - development branch.
