### ISSUE TITLE
Driver module men_lx_m77.ko stops working on hot plug RS-485 connector

### ISSUE THREAD

**Issue by xrombik** [MEN-Mikro-Elektronik/13MD05-90#128]
Compact PCI serial module G204 with 4x UART RS-485 extension card with G22 3U CompactPCI Serial Intel Core i7 CPU Board. Linux Debian 9, x64. Driver module **men_lx_m77.ko** stops working after plugging and unplugging connector RS-485 by several times while data is transferred. `read` system call returns data garbage and after that stops receiving data any more. Even if `close`/`open` file `/dev/sttyD0`, restart program, or re-login does not have any effect. To restore data receiving, i do just unload and load again **men_lx_m77.ko** driver with this commands: 
```
$ modprobe -r men_lx_m77
$ modprobe men_lx_m77 <some arg1> <some arg2>
 ```
And then receiving goes fine again (with respect to `open`/`read`/`write`/`close` system calls). 
This result checked with baud=9600, 8 bit no parity.

**Comment by dpfeuffer** [comment]
I close this issue, because this isn't a supported use case and the unload/load workaround can be used.
