### ISSUE TITLE
13Y004-06 missing file. 

### ISSUE THREAD

**Issue by KonradJPE** [MEN-Mikro-Elektronik/13MD05-90#132]
For 13Y004-06 submodule, file smb2_bmc_api.h is missing. 
File is used by SMB2/TOOLS/SMB2_BMC_CTRL, and LIBSRC/SMB2_BMC_API.

Could you please check if this file is available in MEN repo?

**Comment by dpfeuffer** [comment]
[smb2_bmc_api.zip](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/3367743/smb2_bmc_api.zip)

Please do the usual header cleanup.

**Comment by KonradJPE** [comment]
File added into repo.
