### ISSUE TITLE
line endings of all text files shall be normalized

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#137]
When I edited mdis_drivers_bbis_d201_com.git/DRIVER/COM/bb_d201e.h, I discovered that some source files have CRLF line endings by mistake. To cleanup the line endings in all MDIS repos, I added this new requirement to the 13MD05-90_SwArchSpec:

MEN_13MD05-90_SA_0255	[DES] Repo Line Endings
New
All text files in MDIS repos shall be stored with Unix (LF) line endings. 
Comment: 	Add the following .gitattribute file to each repo, to ensure that text files that any contributor introduces to the repo have their line endings normalized (LF line endings):
```
*		text=auto
```

This causes, that when someone commits a file, Git guesses whether that file is a text file or not, and if it is, it will commit a version of the file where all CR + LF bytes are replaced with LF bytes. It doesn't directly affect what files look like in the working tree, there are other settings that will convert LF bytes to CR + LF bytes when checking out a file.
To prevent that git declares are non text file as text file by mistake and then corrupt any non text file, non text files (pdf, jpg, binaries) should be explicitely designated as non text files within the .gitattribute file:
```
*		text=auto
*.jpg		-text
*.pdf	-text
```

Comment: 	To normlize all text files within an existing repo, you can perform these steps:
```
$ echo "* text=auto" >.gitattributes
$ git add --renormalize .
$ git status        # Show files that will be normalized
$ git commit -m "introduce end-of-line normalization" 
```

**Comment by KonradJPE** [comment]
> All text files in MDIS repos shall be stored with Unix (LF) line endings.
> Comment: Add the following .gitattribute file to each repo, to ensure that text files that any contributor introduces to the repo have their line endings normalized (LF line endings):

Fixed
