### ISSUE TITLE
remove unused SMB submodules

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#138]
It seems that the following SMB related submodules are no longer required under Linux:
-	SMBPCI BBIS: https://github.com/MEN-Mikro-Elektronik/mdis_drivers_bbis_smbpci_com
-	SMB2 Lib: https://github.com/MEN-Mikro-Elektronik/mdis_libsrc_smb2_com

Because I hate unused code that could lead to confusions: Please remove this submodules from 13MD05-90. 
I discussed this with Thomas Schnürer (before he left MEN) and now with Florian. We all think it's ok to remove it. But to be sure, please do some SMB related testing in your test setup (maybe you have already some SMB related test cases).

**Comment by KonradJPE** [comment]
Submodules are removed from 13MD05-90 repository.
After short tests with mdiswiz, I could not create project that is using sources from mentioned submodules. 
If no problems occurs in the coming days I will close the issue.
