### ISSUE TITLE
Fix incorrect MDIS4 notes

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#143]
I found that some MDIS5 LL drivers have incorrect descriptions. E.g.:
```
 *         Name: mmodprg_drv.c
 *      Project: M-module driver (MDIS4)
```
A quick search in the current jpe-dev branches of 13MD05-90 and related submodules shows:
```
[dpfeuffer@vm-manjaro 13MD05-90]$ grep -Hirn "(MDIS4)"
13PP04-06/DRIVERS/MDIS_LL/PP04/DRIVER/COM/pp04_drv_int.h:4: *      Project: PP04 module driver (MDIS4)
13Z010-06/DRIVERS/MDIS_LL/QSPIM/DRIVER/COM/qspim_drv.c:4: *      Project: QSPIM driver (MDIS4)
13Z024-06/DRIVERS/MDIS_LL/MMODPRG/DRIVER/COM/mmodprg_drv.c:4: *      Project: M-module driver (MDIS4)
13M011-06/DRIVERS/MDIS_LL/M011/DRIVER/COM/m11_drv.c:4: *      Project: M11 module driver (MDIS4)
```
I assume, that all MDIS LL drivers at GitHub are MDIS5 drivers, otherwise they couldn't be used with the 13MD05-90 MDIS5 Linux package.

Please correct the note to (MDIS5).
There may be more drivers with wrong MDIS4 notes, but a simple search for "MDIS4" gives too much hits. Please think about a more sophisticated search ;-)

**mmodprg_drv.c**
When you fix the MDIS4 note in 13Z024-06/DRIVERS/MDIS_LL/MMODPRG/DRIVER/COM/mmodprg_drv.c, please change also the wrong description from:
```*  Description: Low-level driver to program M-Module ID on any M-module```
to
```*  Description: Low-level driver to perform 8/16/32-bit read/write access to various HW devices (e.g. M-Modules, 16Z024_SRAM SRAM Controller)```

**Comment by mlassota** [comment]
Fixed
