### ISSUE TITLE
Copyright clearing in doxygen documentation

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#153]
The generated doxygen documentation shall not contain a copyright note.

To archive this, the following steps are necessary:
1. Remove copyright note from https://github.com/MEN-Mikro-Elektronik/13MD05-90/blob/master/MDISforLinux/DOXYGENTMPL/HTML/men_footer.html

Current
```
	<p class="footer">
	Generated for $projectname using <a href="http://www.doxygen.org">doxygen</a>.<br>
	Copyright &copy; 2012 <a href="http://www.men.de">MEN Mikro Elektronik GmbH</a>. All Rights Reserved.
	</p>
```

New

```
	<p class="footer">
	Generated for $projectname using <a href="http://www.doxygen.org">doxygen</a>. All Rights Reserved.
	</p>
```

2. Create new doxygen documentation to test changed men_footer.html

3. Generate new doxygen documentation for all SW modules

**Comment by mlassota** [comment]
Done.
