### ISSUE TITLE
FPGA_LOAD must enable PCI memory regions

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#165]
https://github.com/MEN-Mikro-Elektronik/mdis_tools_fpga_load

fpga_load is mainly used for FPGAs that resides at the PCI(e) bus.
Because UEFI boot doesn't enable the mem regions of PCI devices as the legacy BIOS boot did, users may run into trouble.
Please test if chameleon table can be dumped with fpga_load from any MEN Chameleon FPGA with G25A or F26L CPU and Linux UEFI installation (I assume this will fail).
For Linux: Add code to enable the mem regions of the specified PCI device (e.g. using pci_enable_device() or setpci).
See also #74 and #162.

**Comment by KonradJPE** [comment]
> For Linux: Add code to enable the mem regions of the specified PCI device (e.g. using pci_enable_device() or setpci).

Added, setpci command is used.
