### ISSUE TITLE
fpga_load is not correctly working with mcb and mcb_pci driver

### ISSUE THREAD

**Issue by FlorianRauh** [MEN-Mikro-Elektronik/13MD05-90#167]
Starting from Linux kernel 3.15, modules mcb and mcb_pci are mainline in kernel.
But unfortunately fpga_load tool and mcb driver are interfering each other.

Therefore a hint as **short term solution** in the output of the fpga_load should be displayed:
"In order to run fpga_load correctly under Linux make sure that mcb and mcb_pci drivers are not loaded!"

**Long term solution** could be that fpga_load is not interfering with mcb and mcb_pci driver.

Error case:
```
# fpga_load 0x1a88 0x4d45 0x00d7 0 -t -v

Z100_PCIInit

Update device:
Nr.|bus|dev|fun|   BAR0  |   BAR1  |   BAR2  |   BAR3  |   BAR4  |   BAR5
  0  10   0   0  92201000  0000e001  92000000  92200000  0000ec01  0000e801
*** ERROR: No chameleon table found for PCI device [10](0/0/201) [dom](bus/dev/fun) (0x10009)
*** ERROR: can't find device 0x02d
*** ERROR: Chameleon table or flash interface not found (0x2018)
```
The error case can be easily approched with a F26L and a F614(FPGA)

**Comment by KonradJPE** [comment]
> Therefore a hint as short term solution in the output of the fpga_load should be displayed:
> "In order to run fpga_load correctly under Linux make sure that mcb and mcb_pci drivers are not loaded!"

Added. Please find compiled binary in release-13MD05-90_02_01 branch.
Additionally LINUX mak_switch was added into default fpga_load build.

**Comment by FlorianRauh** [comment]
Dear Konrad, meanwhile I know that the source of the error was not the mcb drivers. 
The FPGA card itself was in a reset state and therefore the FPGA chameleon table was not accessible anymore. This had nothing to do with the mcb drivers. I apologize for a this issue. Please revert to the old source code and close the issue. My fault sorry.

**Comment by KonradJPE** [comment]
@FlorianRauh Does it have to be reverted before 02_01 release?

**Comment by FlorianRauh** [comment]
It´s actually wrong but it´s a tiny issue which is not harming the result in a negative way.  You can leave it for 02_01. 
But for 02_02 revert it please.

**Comment by KonradJPE** [comment]
Fixed
