### ISSUE TITLE
mdiswiz: Properties->General->Driver is empty

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#173]
13MD05-90_02_01_b4
CentOs 8
The "Driver:" line of the General tab of the component properties are always empty.
No functional impact. Don't know if there was a driver description with 13MD05-90_02_00

![image](https://user-images.githubusercontent.com/31008280/70981913-5c209f80-20b6-11ea-9daf-968f83e18735.png)

**Comment by KonradJPE** [comment]
It seems that only IP Cores (16Z*) are affected.

> Don't know if there was a driver description with 13MD05-90_02_00

It was the same.

**Comment by KonradJPE** [comment]
Fixed, new mdiswiz binary available (13MD5-90 branch jpe-dev).
