### ISSUE TITLE
13M047-06: Internal Test Tool M47_TEST missing

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#176]
Discovered during acceptance test for 13MD05-90_02_01_b4:
The internal test tool M47_TEST is missing in https://github.com/MEN-Mikro-Elektronik/13M047-06 but specified in 13m04706.xml.
```
--- 13m04706.xml: MDIS5 driver package for MEN M47 M-Module ---
*** <makefilepath>=DRIVERS/MDIS_LL/M047/TEST/M47_TEST/COM/program.mak not found
    name: m47_test
    desc: Test program for the M47 driver
    type: Driver Specific Tool
    attr: internal="true"
```

Please add it from provided zip:
[TEST.zip](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/3987904/TEST.zip)

**Comment by KonradJPE** [comment]
Added.
