### ISSUE TITLE
scan_system.sh generated Makefile has always /opt/menlinux source path

### ISSUE THREAD

**Issue by mlassota** [MEN-Mikro-Elektronik/13MD05-90#180]
If 'system_scan.sh' is called with custom path, this path doesn't appear in generated Makefile and compilation always uses default path '/opt/menlinux' sources.
This should be fixed to allow compilation from sources from custom path.
Also it seems that compilation doesn't work if the given path is relative. It only works with absolute path.

**Comment by KonradJPE** [comment]
Fixed
