### ISSUE TITLE
13Z077-90 - Test changes merged from feat/i2cWrite branch

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#184]
Please make a functional verification of the changes provided in https://github.com/MEN-Mikro-Elektronik/13Z077-90/pull/2.
The feat/i2cWrite branch was already merged into jpe-dev branch by mistake!
The feat/i2cWrite branch is deleted.

Anyway, I did a code review and now we request you to test:
1) Ethernet communication
2) AC address r/w via the new implemented sysfs z77_eeprod_mac node
For details, see: https://github.com/MEN-Mikro-Elektronik/13Z077-90/pull/2

**Comment by mlassota** [comment]
Tested and merged.
