### ISSUE TITLE
MDISWIZ: EOS note is confusing

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#185]
Today, I was confused of the EOS note in this mdiswiz dialog:

![image](https://user-images.githubusercontent.com/31008280/75679219-7dddfb80-5c8f-11ea-993b-b821270fa306.png)

My first thought was, that all models are EOS (because there is no EOS tag in the Note column).
Then I remembered of the EOS tag if any model is EOS, and that the read text is only the description of the EOS tag.

Please change the description to prevent confusion.
Suggestion:
(black) Note column tags:
(red) EOS: No longer maintained (see supported_components.md)

Please check if it is more obvious.

**Comment by KonradJPE** [comment]
> Please change the description to prevent confusion.
> Suggestion:
> (black) Note column tags:
> (red) EOS: No longer maintained (see supported_components.md)
> Please check if it is more obvious.

Yes, it is more obvious. 
Changed.
