### ISSUE TITLE
General code review for locking of shared resources 

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#205]
Please perform a general code review of common MDIS SW modules (MK, BK, OSS, .. - but not LL drivers).
After we found two locking errors in MDIS (see #200 and #204) there may be more unsafe shared resource.
MDIS must be multithreading as well as SMP save.

**Comment by mlassota** [comment]
Neither Konrad nor I found any significant errors.
