### ISSUE TITLE
Having only one baud_base for all UARTs could be a problem

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#207]
This issue refers to the MAIN_PR006949 problem report.

**Product Number**
13Z025-90

**Detected in Revision**
01_17

**Initiating**
Ferdinand Lenhardt (menFedinandL)

**Description**
There could be constellations with UART instances on different boards with different UART base clocks, which would require to specify a different baud_base in the UART software driver. However only one baud_base for all UARTs can be specified.

**Problem Analysis Result**
The UART software driver is responsible for all UART instances.
The described problem has been reproduced on a test FPGA design with two different UART instances having two different base clocks (29.4912 MHz and 66 MHz, the two typical base clocks in our systems).

**Project Impact/symptom**
If there are UARTs with different base clocks in the system, some of the UARTs would not communicate with the correct baudrate.

**Problem change suggestion**
Introduce a new UART software driver parameter of type string (which overrides baud_base) for being able to specify a different baud base for each of the UART instances.

**Comment by mlassota** [comment]
New parameter added.
