### ISSUE TITLE
MAIN_PR004508 MDIS CPCI hybrid setup not possible

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#22]
_From @michaelmiehling on June 28, 2018 9:32_

**Describe the bug**
It is not possible to setup correctly a CPCI hybrid system with MDIS wizard.
When we set a board in the CPCI-S0 slots, the PCI_PATH is wrong, leading to a board not found error.
Not possible to setup correctly a hybrid system with a F23P CPU desc.

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
 13MD05-90 1.18

**Additional context**

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#14_

**Comment by KonradJPE** [comment]
Detection of boards F205 and G204 have been added into scan_system script. CPCI hybrid system should now be detected correctly by scan_system script. Updated mdiswiz executable that is required to open updated system.dsc file is in commit id: b296745
