### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#224]
Q (dpfeuffer):
Do you have any other suggestions to improve the testing? 

A (jpe):
The test system is complex. I would put configuration into one file and add parameter to specify configuration file. I'd use some simple relay to turn on and off the testing voltage instead of using photo-coupler in Box PC.

**Comment by dpfeuffer** [comment]
Please consider this input to improve testing for the next release.

**Comment by afernandez-tech** [comment]
Please, Can you explain me this changes? what is the number test?
thanks

**Comment by dpfeuffer** [comment]
>what is the number test?

"number test"? I don't understand.

This issue address general improvements for the testing. Please investigate what can be improved. See also the remark from Marcin (jpe) above.

We can also talk about it at the next MDIS meeting.

**Comment by dpfeuffer** [comment]
Jorge and Javier are now in progress to improve the testing. I close this issue because it contains no further helpful info.
