### ISSUE TITLE
scan_system.sh is not finding a G23

### ISSUE THREAD

**Issue by FlorianRauh** [MEN-Mikro-Elektronik/13MD05-90#227]
- Please remove from the "CPU_KNOW_BOARDS="
   "G22A"

- Please add to the "CPU_KNOW_BOARDS="
   "G023-", "G025-" "G025A"

and adapt the corresponding if/case

Please see "MEN Standard for ID-EEPROMs" for additional help

**Comment by dpfeuffer** [comment]
**Please do only the following changes in scan_system.sh:**
```
CPU_KNOWN_BOARDS=
G22- G022 G22A => G22- G022
G23- G23A => G23- G023
```
Remark: "G025" match also to "G025-" and "G025A"

**Comment by afernandez-tech** [comment]
Only do the followings changes:
CPU_KNOWN_BOARDS=
G22- G022 G22A => G22- G022
G23- G23A => G23- G023
