### ISSUE TITLE
scan_system.sh and mdiswiz do not correctly support the F75P

### ISSUE THREAD

**Issue by ghost** [MEN-Mikro-Elektronik/13MD05-90#233]
As described in internal MAIN_PR007815 the scan_system.sh and mdiswiz do not correctly support the F75P.

See attached [system.dsc](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/7677198/system.dsc.txt)
for an example.

**Comment by dpfeuffer** [comment]
There is currently no requirement from PM to support F75P from 13MD05-90. If there is any need, please ask PM how to proceed with it.
