### ISSUE TITLE
MDIS drivers are spamming in kernel log

### ISSUE THREAD

**Issue by M-Gerner** [MEN-Mikro-Elektronik/13MD05-90#234]
Our customer informed us about kernel messages which are created every second on their system, see attached kern.log.
[kern.log](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/7726734/kern.log)
 
We can see this behaviour on different systems with different kernels whenever there is an access to smb. 
Customer is using a Kernel 3.13 but we can also recreate it with Kernel 4.18, 5.4 or newer.
At first we thought it could be the debug level of the driver is pretty high but according to the system.dsc it is the lowest debug level.
[BC50M-system.dsc.txt](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/7726780/BC50M-system.dsc.txt)

**Comment by dpfeuffer** [comment]
This issue is the same as MAIN_PR008003
