### ISSUE TITLE
Blacklisting as described in QUICKSTART.md does not work

### ISSUE THREAD

**Issue by ckloecker** [MEN-Mikro-Elektronik/13MD05-90#238]
QUICKSTART.md states that mcb and mcb_pci shall be blacklisted if present on the system. However, to do so, it tells you to do:
```
  # echo mcb >> /etc/modprobe.d/blacklist.conf
  # echo mcb_pci >> /etc/modprobe.d/blacklist.conf
```

Which is not working at least, for example, for Ubuntu 16.04. Instead it should read:
```
  # echo blacklist mcb >> /etc/modprobe.d/blacklist.conf
  # echo blacklist mcb_pci >> /etc/modprobe.d/blacklist.conf
```

**Comment by mad-jsanjuan** [comment]
This Documentation issue was already fixed with this PR: https://github.com/MEN-Mikro-Elektronik/13MD05-90/pull/206 

To double check I have tested this mechanism as described in the QUICKSTART document:

Without the blacklist entry:

```
men@men:~$ cat /etc/modprobe.d/blacklist.conf | grep mcb
men@men:~$
men@men:~$ lsmod | grep mcb
men@men:~$ sudo modprobe --use-blacklist mcb
men@men:~$ lsmod | grep mcb
mcb                    16384  0
men@men:~$
```

With the blacklist entry:
```
men@men:~$ sudo modprobe -r mcb
men@men:~$ sudo vim /etc/modprobe.d/blacklist.conf
men@men:~$ cat /etc/modprobe.d/blacklist.conf | grep mcb
blacklist mcb
blacklist mcb_pci
blacklist mcb_lpc
men@men:~$ sudo modprobe --use-blacklist mcb
men@men:~$ lsmod | grep mcb
men@men:~$ # nothing loaded
```

**Comment by mad-jrodriguez** [comment]
Looks good to me.

**Comment by dpfeuffer** [comment]
You are right, I just forgot my commit. I close this issue now.
