### ISSUE TITLE
MAIN_PR004291 13MD05-90 mdiswiz f204 F205 G204

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#25]
_From @michaelmiehling on June 28, 2018 9:23_

**Describe the bug**
F204 F205 G204 are not corret in system.dsc 
After build, access to M43 and M58 is not possible by using m_open.
Error message appears: 0x0705: BBIS: wrong BoardID detected

- Slot 1: F23P
- Slot 2: G204 + M36N
- Slot 3: G204 + M58
- Slot 4: G204 + M62N
- Slot 5: G215 

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
 Version [e.g. 13MD05-90 05_01_22 and 13Z077-90 01_01]

**Additional context**
might be related to MAIN_PR004534

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#11_

**Comment by KonradJPE** [comment]
Detection of boards F205 and G204 have been added into scan_system script in commit id: 59b6263.
