### ISSUE TITLE
MAIN_PR004289 13md05-90 mdiswiz error del cpu

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#26]
_From @michaelmiehling on June 28, 2018 9:14_

**Describe the bug**
After deleting the current cpu in the mdiswizard, the mdiswizard closes itself automatically

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
13MD05-90 1.20rc2

**Additional context**

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#10_

**Comment by KonradJPE** [comment]
New mdiswiz executable added in commit id: 6d140c9. Corresponding commit with mdiswiz sources: 13Y008-90 id: e9e61a0.
