### ISSUE TITLE
Check that all submodules are in release state prior 13MD05-90 testing

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#262]
Each submodule shall be in release state to be ready for the 13MD05-90 release.
For each submodule:
- all open pull requests shall be handled:
  - pull requests shall be merged into the mad_dev branch for testing
  - mad_dev branch shall be tested
  - mad_dev branch shall be merged into master branch
- the master branch shall be tagged with the release version

**Comment by mad-jsanjuan** [comment]
When reviewing the current status of all the project repos I found a few open branches that may need discussion:

1) Style changes in https://github.com/MEN-Mikro-Elektronik/13Z077-90/pull/11 . These are outdated and merging this will require a merge conflict resolution.
2) There is some work that was not merged at https://github.com/MEN-Mikro-Elektronik/13Z015-06/compare/mad-dev-10_14 . Don't know whether this this is necessary or not. It seems to only affect some tools but I am missing some context there from poor explanation on the commit messages.
3) The main repo 13MD05-90 has this really old branch that does not apply cleanly:  https://github.com/MEN-Mikro-Elektronik/13MD05-90/compare/thomas-msi-support-2

Other repos seem to have specific custom release branches for specific customers that we should probably leave them as is.
