### ISSUE TITLE
MAIN_PR004235 13MD05-90 mdiswizard 13SC24_IC 16Z077

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#29]
_From @michaelmiehling on June 28, 2018 9:5_

**Describe the bug**
13MD05-90 mdiswizard:
- An IPcore called "13SC24_IC" could be choosen, the number "13" sounds strange to me.
- 

IP core entry "16Z077" should be deleted

See picture attached
![13md05-90mdiswizard](https://user-images.githubusercontent.com/23742250/42024679-07027b9e-7ac3-11e8-8175-ffa256664152.png)

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
13MD05-90 1.20-rc2

**Additional context**

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#7_

**Comment by KonradJPE** [comment]
13SC24_IC and 16Z077 IPCore do not appear in the latest version of mdiswiz.
