### ISSUE TITLE
mad-dev: Generated Makefile has broken includes

### ISSUE THREAD

**Issue by areitz86** [MEN-Mikro-Elektronik/13MD05-90#294]
![image](https://user-images.githubusercontent.com/79543787/227511146-af509314-5aca-4177-8c85-a354120cdaed.png)

![image](https://user-images.githubusercontent.com/79543787/227511488-5759de74-a768-4075-bb8b-9e17bf527e55.png)

Generated Makefile from MDIS scan has wrong file extensions in last entry per block. Other entries have a continuation slash, even though there no next line.

**Comment by areitz86** [comment]
Commit: **https://github.com/MEN-Mikro-Elektronik/13MD05-90/commit/5bb36c83baac4722b9649991c4ab06500d5e653e**

**Comment by mad-jsanjuan** [comment]
Hi @areitz86 ,

Could you provide us with more information about your system info? What Linux distro are you using when you get this behavior with the file extension? What does `bash --version` say? 

regards,
Jorge

**Comment by areitz86** [comment]
hey @mad-jsanjuan,

bash version is 4.2.46(2) (x86_64-redhatz-linux-gnu) on Scientific Linux (RHEL) 7.4.

Cheers,
Andreas

**Comment by mad-jsanjuan** [comment]
@areitz86 . This Scientific Linux (RHEL 7.4) is not officially supported by MDIS 13MD05-90. Please check https://github.com/MEN-Mikro-Elektronik/13MD05-90/blob/mad-dev/supported_components.md although this still needs updating for the upcoming release. 

We have however looked into making the scan script a bit more flexible and it should not add this extra quotation marks anymore.

**Comment by areitz86** [comment]
Thank you. I was aware that RHEL7.4 is not supported. However, my thought was, that the scanning is depending on standard utils like bash,sed,etc., it should not fail on old but standard userspace tools.
Thank you really much for looking into it. Will check and report back, but close the issue for now.
