### ISSUE TITLE
MAIN_PR004144 13Z044-90 not supported in mdiswiz

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#30]
_From @michaelmiehling on June 28, 2018 9:3_

**Describe the bug**
It would be nice it would be possible to include the 13Z044-90 display driver into the mdiswizard and use it.
The documentation is so old and not usable anymore.
Therefor it would be much easier if it would work with mdiswiz intuitively

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
13MD05-90 1.20beta5

**Additional context**

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#6_

**Comment by KonradJPE** [comment]
In new mdiswiz executable (v2.05.00) module 16Z044_FB is available.
