### ISSUE TITLE
MAIN_PR004068 13MD05-90 mdisiwzard Template G25A

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#31]
_From @michaelmiehling on June 28, 2018 9:1_

**Describe the bug**
The template of the G25A does not include the generic SMBus (smb2_2) in mdiswizard.

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
13MD05-90 1.20 beta 4

**Additional context**

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#5_

**Comment by KonradJPE** [comment]
Added support for generic SMBus in scan_system script - boards G25, F23, F26. 
After performing scan_system script, generic SMBus is visible in mdiswiz for above CPU boards.
