### ISSUE TITLE
MAIN_PR004032 13MD05-90 F26L missing in mdiswiz

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#32]
_From @michaelmiehling on June 28, 2018 9:1_

**Describe the bug**
F26L missing in mdiswiz. urgently needed for the new customer project (3x(F26L+F204+M51+G211))
Goal new D10 to be used for customer. Customer has 100ds of M51 in field --> therefore backward compatibility is necessary.

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
13MD05-90 1.20beta5

**Additional context**

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#4_

**Comment by KonradJPE** [comment]
Added new version of mdiswiz with F26L support. New executable available in commit 249680a on branch jpe-dev.
