### ISSUE TITLE
MAIN_PR003931 G25A MDIS5 wizard scan_system.sh 13MD05-90

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#33]
_From @michaelmiehling on June 28, 2018 7:56_

**Describe the bug**
The current version of MDIS5 1.20 beta 3 is not fully supporting the SMBus.
1.) It´s possible to get access to the BMC but not to the SMBus which leads to the backplane -> AF02.
A rework of the scan_system.sh is needed.
2.) All SMB2_tools should be available in the properties of mdiswizard.

I added a Makefile with some smb2 tools added manually
I added a system.dsc with access to generic SMBus added manually.

**To Reproduce**

**Expected behavior**

**Screenshots and logs**
If applicable, add screenshots or logs to help explain your problem.

**Revision of 13MD05-90 and related driver or module where the bug was detected**
13MD05-90 V1.20 beta 3

**Additional context**
[MDIS.zip](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/2144309/MDIS.zip)

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#3_

**Comment by KonradJPE** [comment]
Added support for SMBus in scan_system script - boards G25, F23, F26. All necessary drivers/tools are added into Makefile. 
After performing scan_system script SMB2_tools are visible in mdiswiz.
