### ISSUE TITLE
MAIN_PR005137 MDIS Wizard Support for A25

### ISSUE THREAD

**Issue by michaelmiehling** [MEN-Mikro-Elektronik/13MD05-90#36]
_From @michaelmiehling on June 28, 2018 9:43_

**Describe the bug**
A25 support must be implemented in MDIS Wizard

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

**Revision of 13MD05-90 and related driver or module where the bug was detected**
 mdiswiz 2.21

**Additional context**

_Copied from original issue: MEN-Mikro-Elektronik/13MD05-90_old#21_

**Comment by JSierl** [comment]
please postpone this topic until week 28 when we know for sure if VME has to be supported in the next version

**Comment by KonradJPE** [comment]
Added into mdiswiz.
Support for A25 is also mentioned in: 
https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/149
