### ISSUE TITLE
Scan_system makefile incorrectly configured and causing project builds to fail

### ISSUE THREAD

**Issue by bmoore84** [MEN-Mikro-Elektronik/13MD05-90#41]
**Version of MDIS/OS version/Hardware**
- jpe-dev branch of MDIS project
- Ubuntu 16.04 LTS / Kernel 4.4.0-116-generic
- 08SC24-02

**Bug Description**
The scan_system script is adding a line in the Makefile pointing to a driver that doesnt exist:
![image](https://user-images.githubusercontent.com/42809192/44795113-3104fa80-abaa-11e8-9dcc-6b98e952b003.png)

Attempting to build a project will result with:
![image](https://user-images.githubusercontent.com/42809192/44795152-50038c80-abaa-11e8-9823-00a6bcc85bce.png)

Removing "DRIVERS/I2C_BUSSES/i2cpiix4/driver.mak" from "ALL_NATIVE_DRIVERS ="  will allow the project to build successfully.

**Comment by mlassota** [comment]
I removed this driver from compilation so it won't make problems anymore.
