### ISSUE TITLE
Error when saving/building projects as a normal user

### ISSUE THREAD

**Issue by bmoore84** [MEN-Mikro-Elektronik/13MD05-90#47]
**Description**
Error generated when saving or building project as normal user.
Despite the error, it seems the configurations are still saved/built.
When running wizard as root, this issue does not occur. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42809192/45741004-d71ab200-bbf6-11e8-929a-908a159e085a.png)

**Expected behavior**
Save/build project as a normal user without error

**Where detected**
Ubuntu 16.04.5 Kernel 4.15

**Comment by mlassota** [comment]
There have been couple of changes in MDIS Wizard since you've reported this error, thus it might have been solved before I looked at it, because I was unable to reproduce it.
Could you please try to recreate it with the latest binary?

**Comment by bmoore84** [comment]
Hello Marcin,
I will test again and see what is different.
Thanks for the update.

Best regards,

Blake

Blake Moore
Customer Support
MEN Mikro Elektronik GmbH
Neuwieder Straße 3-7
90411 Nürnberg, Germany
Phone +49 911 99 33 5 - 253
Fax +49 911 99 33 5 - 901
Blake.Moore@men.de<mailto:Blake.Moore@men.de>
www.men.de<http://www.men.de>

> Subscribe to our newsletter<https://www.men.de/news-media/newsletter/>

MEN Mikro Elektronik GmbH - Bernd Härtlein (CEO) - Yilmaz Kocak (CFO)  - Handelsregister/Trade Register AG Nürnberg HRB 5540
Please consider the environment before printing this e-mail

**Comment by bmoore84** [comment]
After looking into this issue further, I decided this can be closed. A normal user shouldnt be allowed to create/build/save a configuration since you must be root to run the scan system script and to use "make". 
With root permissions, everything works as expected.
