### ISSUE TITLE
automatically scanning M-Modules and it´s Carriers doesn´t work yet perfectly

### ISSUE THREAD

**Issue by FlorianRauh** [MEN-Mikro-Elektronik/13MD05-90#48]
1) The Slot number in mdiswiz is wrong
![mmoduelescan](https://user-images.githubusercontent.com/40606803/46142677-40c63c00-c247-11e8-86b2-b1c92afa8ae3.png)
The CPU is always Slot 1 and then it will be counted up into bot directions (CPCI and CPCIs). In this case it should have been Slot 3.
An automatic scan with just this Carrier worked successfully
05:0e.0 Bridge: Altera Corporation Device d203 (rev e3).
2) If I plug in a second Carrier, all Modules are not working. The reason could be that the order of the Carrier is mixed up.

Further hints: lspci is counting from "f" to "0" . "f" is the most far away Slot seen from the CPU.
05:0e.0 Bridge: Altera Corporation Device d203 (rev e3).  //first F205 Carrier
05:0f.0 Bridge: Altera Corporation Device d203 (rev e3).   //second F205 Carrier

**Comment by FlorianRauh** [comment]
More Details and Hardware to test will follow

**Comment by mlassota** [comment]
Fixed
