### ISSUE TITLE
'Make' fails when building a manually created project

### ISSUE THREAD

**Issue by bmoore84** [MEN-Mikro-Elektronik/13MD05-90#51]
**Description**
Manually creating a project fails when attempting to 'make'. If the scan system option is used in the wizard or via command line, the project is built successfully.

**Examples of issue**
![image](https://user-images.githubusercontent.com/42809192/46800781-084f5380-cd59-11e8-8d26-560e6e1b072f.png)

**Expected Behavior**
To be able to build a project that manually and automatically created without error

**Where Detected**
Ubuntu 16.04.5 LTS Kernel 4.15.0-34-generic

**Comment by mlassota** [comment]
Fixed
