### ISSUE TITLE
Improve install script usability

### ISSUE THREAD

**Issue by JSierl** [MEN-Mikro-Elektronik/13MD05-90#53]
to be defined in detail by Florian Rauh

**Comment by FlorianRauh** [comment]
1.
During ./INSTALL a message appears
"copy .git to /opt/menlinux...ok"
why is this being done? Does it make sense.

2. Why am I being ask to overwrite? 
"Overwrite folder /opt/menlinux/TOOLS/M_TMR (y/n/q): y"
Does this make sense?

**Comment by mlassota** [comment]
>     1. During ./INSTALL a message appears
>        "copy .git to /opt/menlinux...ok"
>        why is this being done? Does it make sense.

It doesn't. Having .git directories in installation point serves no purpose.
Fixed.

>     2. Why am I being ask to overwrite?
>        "Overwrite folder /opt/menlinux/TOOLS/M_TMR (y/n/q): y"
>        Does this make sense?
It doesn't.
Fixed.
