### ISSUE TITLE
complete MDIS zip file is needed

### ISSUE THREAD

**Issue by FlorianRauh** [MEN-Mikro-Elektronik/13MD05-90#54]
Goal is to have one zip file including MDISforLinux and all submodules. Right now only folder of submodules are available in the zip file.
![zipfile](https://user-images.githubusercontent.com/40606803/46866534-10bf9100-ce22-11e8-9fe8-0c983bc9841b.png)

**Comment by KonradJPE** [comment]
Unfortunately it is not possible via 'git archive' to create archive with submodules code in GitHub automatically.
For releases, complete archive must be created and added manually.
