### ISSUE TITLE
Unable to use mdis_createdev tool

### ISSUE THREAD

**Issue by bmoore84** [MEN-Mikro-Elektronik/13MD05-90#55]
**Description**
System:
G23 + G204 with M77N
To be able to load the men_lx_m77 module, you must first run "mdis_createdev -b d203_a24_1", however this fails with:
![image](https://user-images.githubusercontent.com/42809192/46872298-ff7f8000-ce33-11e8-8540-67c77019eed2.png)
The error presents itself even when running the tool without any arguments. 
libmdis_api.so does exist but cannot be found.

**Expected Behavior** 
To be able to create the device and load the necessary module for the G204 and M77N to function.

**Where detected**
CentOS 7.5.1804  Kernel 3.10.0-862.14.4.el7.x86_64 with latest release from Latest

**Comment by bmoore84** [comment]
Would it be possible for JPEmbedded to set up a system with same hardware, build a project, and run the following commands:
modprobe men_bb_d203_a24
modprobe men_mdis_kernel
mdis_createdev -b d203_a24_1
modprobe men_lx_m77 devName=m77_1 brdName=d203_a24_1 slotNo=0 mode=2,2,2,2 echo=0,0,0,0

**Comment by mlassota** [comment]
This is problem related to distro not to MDIS, and I think we should not try to fix it with installation or makefile scripts for security reasons.
'make install' installs all libraries in '/usr/local/bin', and unfortunatelly CentOS is not configured to look up for libraries in there. To make it look up for them in there you have to:
1. create file '/etc/ld.so.conf.d/libc.conf'
2. put those two lines below into and save:
\# libc default configuration
/usr/local/lib
3. run 'sudo ldconfig - v' to make ldconfig discover new libraries.

Should you have any problems with 'command not found' while running as root, you have to:
1. run 'sudo visudo'
2. add  paths '/usr/local/sbin:/usr/local/bin' to 'secure_path' variable. This will look like that:
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
3. save
4. reboot the system (probably)
