### ISSUE TITLE
revise readme, think about adding MDIS documentation

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#58]
MDISforLinux is not a repo. Please remove https://github.com/MEN-Mikro-Elektronik/13MD05-90/blob/master/MDISforLinux/README.md.

Revise top level readme https://github.com/MEN-Mikro-Elektronik/13MD05-90/blob/master/README.md:
- "Containing toplevel repository ..." --> it is the toplevel repo
- add short explanation about sub dirs and submodules
- Readme shall be user friendly for customers without any MDIS experience. Add short explanation what MDIS is and where it is described in detail.

I suggest to include the MDIS documentation (MDIS5 under Linux User Manual, MDIS5 Developer Guide) from https://www.men.de/software/13md05-90. This is tbd.

**Comment by JSierl** [comment]
This file only needs installation instructions for the case a user downloaded the ZIP from MENs homepage. No GitHub instructions necessary.

**Comment by mlassota** [comment]
Fixed
