### ISSUE TITLE
scan_system.sh: set Makefile LIB_INSTALL_DIR distro specific

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#63]
Default in Makefile: LIB_INSTALL_DIR = /usr/local/lib causes library load error under CentOS, e.g.:
m_rev_id: error while loading shared libraries: libmdis_api.so: cannot open shared object file: No such file or directory

CentOS 7.5 64-bit:
- /usr/local/lib is not in the lib search path
- 64-bit libs should be installed under /usr/lib64

=> Set LIB_INSTALL_DIR in Makefile distro specific (at least for the official supported distros)
Remark: export LD_LIBRARY_PATH=/usr/local/lib is a workaround but not comfortable for the customers

**Comment by mlassota** [comment]
Fixed
