### ISSUE TITLE
SC31 SMBus number wrong in system.dsc after scan_system.sh was executed

### ISSUE THREAD

**Issue by HIttner** [MEN-Mikro-Elektronik/13MD05-90#64]
doing a system scan in Lubuntu 18.04 leads to an incorrect smbus number.
During execution of script, smbus number is e.g. detected as 12 because the board info eeprom (0x57) is only located there.
i2c_i801 is loaded during startup (uncommented in /etc/modules-load.d/blacklist.conf
Afterwards, when checking system.dsc there is a different SMBus Nr. written (e.g. 0x9)
SMBus Scan:
![grafik](https://user-images.githubusercontent.com/43148084/49147114-13a80f80-f304-11e8-84f0-c7e068d8d111.png)
System Scan:
![grafik](https://user-images.githubusercontent.com/43148084/49147181-3f2afa00-f304-11e8-9577-623a59774f82.png)
system.dsc
![grafik](https://user-images.githubusercontent.com/43148084/49147232-6b467b00-f304-11e8-8f62-fca13b4ebf4d.png)
![grafik](https://user-images.githubusercontent.com/43148084/49147301-a183fa80-f304-11e8-97bb-5c65bb9fff8b.png)

**Comment by JSierl** [comment]
Is related with BL71E and must thus be resolved in order to meet the requirements we agreed on in the workshop
