### ISSUE TITLE
failure during make process, Kernel 4.14.93

### ISSUE THREAD

**Issue by M-Gerner** [MEN-Mikro-Elektronik/13MD05-90#69]
Using a Ubuntu 18.04 with kernel 4.14.93-041493-generic I tried to make a project with a F26L, a F205 and a M99.
It was always stopped at the same point of the buildprocess.
![grafik](https://user-images.githubusercontent.com/46787512/51331231-8b2f2b00-1a79-11e9-9342-cd6052c64579.png)
[buildprocess.txt](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/2769320/buildprocess.txt)

At first I removed the the m99 and the F205 from the project.
I tried this process with the latest version of the developers branch on github as well as the master branch and a older mdis version (13mdis05-90_01_20).

[content_makefile.txt](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/2769366/content_makefile.txt)
[content_systemdsc.txt](https://github.com/MEN-Mikro-Elektronik/13MD05-90/files/2769367/content_systemdsc.txt)

**Comment by JSierl** [comment]
probably a duplicate/same error as handled during pull request #67

**Comment by KonradJPE** [comment]
fixed by merge https://github.com/MEN-Mikro-Elektronik/13MD05-90/pull/67
