### ISSUE TITLE
MDIS Wizard erroneous and outdated

### ISSUE THREAD

**Issue by JSierl** [MEN-Mikro-Elektronik/13MD05-90#73]
This Issue is a spinoff from #21 some of it might already be fixed:
    * initial popup: the warning in red is strange. And 'klick' is wrong.
      "To generate an initial config (scan system) klick Cancel and use button 'scan' ..."
    * gksudo: command not found
      And in the next line it says 'finished' instead of 'error'
    ~~* Project/Settings -> DEVNODE_INSTALL_DIR
      /dev is not persistent nowadays~~
    * Project/Save_as --> Cancel pops up an error message

**Comment by KonradJPE** [comment]
>  initial popup: the warning in red is strange. And 'klick' is wrong.

The  warning is now in black,

>  gksudo: command not found
> And in the next line it says 'finished' instead of 'error'

This was already fixed in previous updates,

> Project/Save_as --> Cancel pops up an error message

Fixed.
