### ISSUE TITLE
F26L with G204 is not working correctly in all slots. 

### ISSUE THREAD

**Issue by KonradJPE** [MEN-Mikro-Elektronik/13MD05-90#79]
F26L with G204 is not working correctly in some slots. 
Further informations will be added.

**Comment by JSierl** [comment]
Probably a BIOS bug. Waiting for Team CP (MEN)

**Comment by KonradJPE** [comment]
This issue is strictly connected with https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/74. Therefore I close this issue.
