### ISSUE TITLE
G25A with G215 is not working correctly

### ISSUE THREAD

**Issue by KonradJPE** [MEN-Mikro-Elektronik/13MD05-90#80]
It turns out, that whether G215 works or not depends on what slot it occupies in the back-plane.
Moreover it depends on whether there is a slot occupied or not next to it.
**For instance in this configuration the G215 works:**
G25A03|G214|G204+M77|G204+M35|G215
**In this configuration the G215 does not works:**
G25A03|G214|G204+M77|free|G215
G215 does not work because it goes to D3 state.

**Comment by JSierl** [comment]
Probably a HW bug. New G25 is sent to JPE

**Comment by KonradJPE** [comment]
It seems that described behaviour is connected with backplane bug. After changing the rack (to 0701-0056) issue cannot be reproduced.
