### ISSUE TITLE
Release package - requirements.

### ISSUE THREAD

**Issue by KonradJPE** [MEN-Mikro-Elektronik/13MD05-90#88]
Before creating a release package (e.g. 13MD05-90_02_01.zip):
a) HISTORY dir should be created by INSTALL script,
b) the .git folder must be deleted manually or from a make-delivery-script.

In case of copyrights update, this lines should be updated in all sources -- remove (c). 
Copyright (c) <year_of_file_creation>-<year_of_last_file_change>, MEN Mikro Elektronik GmbH
Copyright <year_of_file_creation>-<year_of_last_file_change>, MEN Mikro Elektronik GmbH

**Comment by KonradJPE** [comment]
> In case of copyrights update, this lines should be updated in all sources -- remove (c).
> Copyright (c) <year_of_file_creation>-<year_of_last_file_change>, MEN Mikro Elektronik GmbH
> Copyright <year_of_file_creation>-<year_of_last_file_change>, MEN Mikro Elektronik GmbH

fixed

**Comment by dpfeuffer** [comment]
I close this issue because you wrote it is fixed.
