### ISSUE TITLE
mdiswiz: manually added SMB bus shall be named like scanned config

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#92]
mdiswiz 3.00.030-linux-14.0

Manually added SMB bus instance is named as "smb2_1":
![mdiswiz_manual_smb](https://user-images.githubusercontent.com/31008280/54433074-40552b00-472b-11e9-91ad-b8b3c269f243.png)

It shall be named like in the scanned configuration "smb2_bus0":
![mdiswiz_scan_smb](https://user-images.githubusercontent.com/31008280/54433106-58c54580-472b-11e9-9e26-55c824354b5a.png)

**Comment by KonradJPE** [comment]
Now default 'Component name' for Model SMBPCI_xxx   is smb2_bus.
