### ISSUE TITLE
driver revision strings shall indicate submodule revision tags

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#94]
The MDIS revision strings that can be queried with M_getstat(M_MK_BLK_REV_ID) from each MDIS driver shall indicate the GIT revision tags of the low-level driver and kernel lib repos.
The revision strings are currently hard coded in the belonging source files (were stamped from MCVS during check-in).
We have to evaluate how the revision strings could be supported in Git. tbd.

Example:
```
[root@mdis4lin mproj_wizscan]# m_rev_id gpio_3
-----[ MDIS Kernel ]-----
MK - MDIS Kernel: $Id: ident.c,v 2.0 2003/02/21 13:34:33 kp Exp $
-----[ Low Level Driver ]-----
Z17 - Z17 low level driver: $Id: z17_drv.c,v 1.15 2017/05/03 16:52:05 DPfeuffer Exp $ Z34/Z37 model
DESC - Descriptor Decoder: $Id: desc.c,v 1.16 2010/09/02 15:15:08 UFranke Exp $
OSS - MEN Linux Operating System Services: %FSREV LINUX/LIBSRC/oss 2.15 2012-08-07%
-----[ BBIS Kernel ]-----
BK - BDIS Kernel: $Id: bk_module.c,v 1.9 2014/07/29 14:35:51 ts Exp $
-----[ BBIS Driver ]-----
CHAMELEON -   Base Board Handler: $Id: bb_chameleon.c,v 1.48 2013/11/28 17:00:05 ts Exp $
DESC - Descriptor Decoder: $Id: desc.c,v 1.16 2010/09/02 15:15:08 UFranke Exp $
OSS - MEN Linux Operating System Services: %FSREV LINUX/LIBSRC/oss 2.15 2012-08-07%
```

**Comment by dpfeuffer** [comment]
After my evaluation how the revision strings could be supported in Git, here are the requirements how to fix it (and how to clean up some outdated MCVS stuff): 

# Overview of MCVS related fields 

| Versions Info                | Location    | Inserted (MCVS)   |  Used for |
| ---------------------------- | ----------- | ----------------- | --------- |
| $Date: 2019/04/29 10:46:01 $ | source file | at file checkin   | -         |
| $Revision: 1.2 $             | source file | at file checkin   | -         |
| $Header: r:/./WINDOWS/TEST/MCVS_FIELDS/mcvs_fields.txt,v 1.4 ... $ | source file | at file checkin | - |
| $Id: mcvs_fields.txt,v 1.1 2019/04/29 13:09:32 DPfeuffer Exp $     | source file | at file checkin | M_getstat(M_MK_BLK_REV_ID) |
| $Log: mcvs_fields.txt,v $ <br> Revision 1.1  2019/04/29 13:09:32  DPfeuffer <br> Initial Revision | source file | at file checkin | - |
| %FSREV WINDOWS/TEST/mcvs_fields 1.1 2019-04-29% | source file | at FILESET checkin | M_getstat(M_MK_BLK_REV_ID) |
| \<date\>2019-04-29\</date\>   | .xml file | at FILESET checkin | mdiswiz package date |
| \<revision\>1.3\</revision\>  | .xml file | at FILESET checkin | mdiswiz package rev |


## Required modifications for clean MCVS to Git migration
The old MCVS fields are no longer updated from Git. The stamped information in source files (*.c,*.h,*.mak,...) are outdated and confusing.

### R1: The following lines with MCVS fields shall be removed in all source files
- $Date
- $Revision
- $Header
- $Id (if not used in variable assignment!)
- $Log (already done)

### R2: The following lines shall be modified in all source files
- The $Id/%FSREV lines in *.c/*.h files shall be changed for Git usage
  Example:
  ```static const char IdentString[]=MENT_XSTR(MAK_REVISION);```
  Notes:
  - This line must be placed somewhere after ```#include <MEN/men_typs.h>``` because of the used MENT_XSTR macro.
  - In pgrogram sources, it must be checked that the revision information will be properly displayed at runtime.
- Some Author lines have two $ signs by mistake. Please remove it.
  Example:
  ```
  $Author: cs $
  ```
  ==>
  ```
  Author: cs
  ```
- The "(MDIS V4.x)" and "MDIS 4.0" like strings in source comments shall be removed:
  Example:
  ```
  Project: M99 module driver (MDIS V4.x)
  ```
  ==>
  ```
  Project: M99 module driver
  ```

See https://github.com/MEN-Mikro-Elektronik/13M099-06/pull/1

### R3: All belonging *.mak files shall be modified to support Git version information

Example:
```
# the next line is updated during the MDIS installation
STAMPED_REVISION=

DEF_REVISION=MAK_REVISION=$(STAMPED_REVISION)
MAK_SWITCH=$(SW_PREFIX)MAC_MEM_MAPPED \
           $(SW_PREFIX)$(DEF_REVISION)
```

See https://github.com/MEN-Mikro-Elektronik/13M099-06/pull/1

### R4: INSTALL.sh shall update the "STAMPED_REVISION=..." line in .mak files
During MDIS installation, INSTALL.sh shall update the "STAMPED_REVISION=..." line of all *.mak files, if this line exists.
The following git commit information of the repo (13MD05-90 or submodule) where the .mak file belongs to shall be assigned to STAMPED_REVISION: 
```STAMPED_REVISION="<tag-numberOfCommits-abbrevCommit>_<date>"```

Where:
- \<tag-numberOfCommits-abbrevCommit\> is the result of ```git describe --dirty --long --tags --always```
- \<date\> is the result of ```git --no-pager show -s --date=short --format=format:"%cd%n"```

Example:
```
dpfeuffer@vm-suse:~/work/repos/13MD05-90> git describe --dirty --long --tags --always
13MD05-90_02_00-3-g3a9cd49-dirty
dpfeuffer@vm-suse:~/work/repos/13MD05-90> cd 13M099-06/
dpfeuffer@vm-suse:~/work/repos/13MD05-90/13M099-06> git describe --dirty --long --tags --always
13M099-06_02_15-0-g31531d1-dirty
dpfeuffer@vm-suse:~/work/repos/13MD05-90/13M099-06> 

dpfeuffer@vm-suse:~/work/repos/13MD05-90/13M099-06> git --no-pager show -s --date=short --format=format:"%cd%n"
2019-02-21

```
Example:
```STAMPED_REVISION="13M099-06_02_15-0-g31531d1-dirty_2019-02-21"```

See https://github.com/MEN-Mikro-Elektronik/13M099-06/pull/1

### R5: INSTALL.sh shall update the \<date\> and \<revision\> strings in .xml files
During MDIS installation, INSTALL.sh shall update the \<date\> and \<revision\> strings in all PackageDesc xml files.
The following git commit information of the repo (13MD05-90 or submodule) where the .xml file belongs to shall be used: 
- \<revision\>: result of ```git describe --dirty --long --tags --always```
- \<date\>: result of ```git --no-pager show -s --date=short --format=format:"%cd%n"```

Example:
```
<date>2019-02-21</date>
<revision>13M099-06_02_15-0-g31531d1-dirty</revision>
```

### R6: The revision info of all used SW modules shall be updated
Not only the revision info of Low-Level driver packages are affected but also the libs and other modules (see M_getstat(M_MK_BLK_REV_ID) revision info example output below).
Therefore, R1..3 applies not only to Low-Level driver packages!

### R7: The fileset revision info in *Doxyfile* files shall be removed
The following line shall be removed in all *Doxyfile* files:
PROJECT_NUMBER = "... $(MEN_FILESET_REVISION)"
The PROJECT_NAME line in *Doxyfile* files is sufficient to describe the documentation scope.
Example:
- Line to remove: ```PROJECT_NUMBER         = "for USR_OSS Linux fileset $(MEN_FILESET_REVISION)"```
- Line to keep: ```PROJECT_NAME           = "USR_OSS library for Linux"```

## Supported Revision Information
With the changes above, and this modifications:
- Pull request to add stringize macros to men_typs.h:  https://github.com/MEN-Mikro-Elektronik/mdis_include_com_men/pull/1
- Pull request to add version info to kernel modules: https://github.com/MEN-Mikro-Elektronik/13MD05-90/pull/115

MDIS supports the following revision info:

### Kernel module version info
```
[root@mdis4lin mproj_m99]# modinfo men_ll_m99
...
version:        13M099-06_02_15-0-g31531d1-dirty_2019-02-21
...
```

### MDIS-API M_getstat(M_MK_BLK_REV_ID) revision info

```
[root@mdis4lin mproj_m99]# m_rev_id m99_1
-----[ MDIS Kernel ]-----
MK - MDIS Kernel: $Id: ident.c,v 2.0 2003/02/21 13:34:33 kp Exp $
-----[ Low Level Driver ]-----
13M099-06_02_15-0-g31531d1-dirty_2019-02-21
MBUF - Buffer Manager: $Id: mbuf.c,v 1.18 2010/04/21 16:51:11 CRuff Exp $
DESC - Descriptor Decoder: $Id: desc.c,v 1.16 2010/09/02 15:15:08 UFranke Exp $
OSS - MEN Linux Operating System Services: %FSREV LINUX/LIBSRC/oss 2.15 2012-08-07%
-----[ BBIS Kernel ]-----
BK - BDIS Kernel: $Id: bk_module.c,v 1.9 2014/07/29 14:35:51 ts Exp $
-----[ BBIS Driver ]-----
D203    Base Board Handler: $Id: bb_d203.c,v 1.18 2013/11/28 17:00:24 ts Exp $
DESC - Descriptor Decoder: $Id: desc.c,v 1.16 2010/09/02 15:15:08 UFranke Exp $
OSS - MEN Linux Operating System Services: %FSREV LINUX/LIBSRC/oss 2.15 2012-08-07%
```

### Revision info from tools

```
[root@mdis4lin mproj_m99]# m99_latency
...
13M099-06_02_15-0-g31531d1-dirty_2019-02-21
(c) 2003..2010 by MEN mikro elektronik GmbH
```

### MDIS Wizard revision info about installed packages

mdiswiz: Packages --> Show Installed
13m09906    13M099-06_02_15-0-g31531d1-dirty

**Comment by dpfeuffer** [comment]
Because this issue affects nearly all 13MD05-90 submodules and we are currently investigate the MDIS license usage, the issue https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/116 should also be considered during the modifications of the submodules to reduce the workload.

**Comment by KonradJPE** [comment]
According to git commands in R4, R5:

```
    <revision>: result of git describe --dirty --long --tags --always
    <date>: result of git --no-pager show -s --date=short --format=format:"%cd%n"
```
We have decided that .git directory will not be provided with release package, so we cannot obtain any data from git directly. https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/61

For release package HISTORY dir is provided. For every submodule below files are available:
```
        git log > 13MD05-90_history.txt"
        git remote -v > 13MD05-90_url.txt"
        git rev-parse --verify HEAD > 13MD05-90_version.txt"
        git describe --exact-match --tags $(git rev-parse --verify HEAD)  &> "/13MD05-90_tag.txt"
```
Questions are:
1. Should we create another file with results of below commands that will be added to HISTORY dir? 
```
    <revision>: result of git describe --dirty --long --tags --always
    <date>: result of git --no-pager show -s --date=short --format=format:"%cd%n"

```
2. Or should we change the definition of STAMPED_REVISION
`STAMPED_REVISION="<tag-numberOfCommits-abbrevCommit>_<date>" `
to data that are already available in HISTORY files ? example: 
`STAMPED_REVISION="<commit_id>_<tag - (only if available)>" `

**Comment by dpfeuffer** [comment]
I'm confused.
Yes, you are right, we decided to remove .git from the delivery package, but it is still included in the 13MD05-90_02_00 release archive files. See https://github.com/MEN-Mikro-Elektronik/13MD05-90/releases/tag/untagged-0cf3f14fb95f35efe031
The HISTORY dir is present after the MDIS installation under /opt/menlinux.
Therefore, I assumed, that the INSTALL script gets the git information with git from .git folder and I forgot decission #61 .
When I look into the /opt/menlinux/HISTORY/* files, I see that all submodules url and version points to 13MD05-90:
```
dpfeuffer@vm-suse:/opt/menlinux/HISTORY> cat 13M034-06_url.txt 13M066-06_url.txt 13Y004-06_url.txt
origin  https://github.com/MEN-Mikro-Elektronik/13MD05-90 (fetch)
origin  https://github.com/MEN-Mikro-Elektronik/13MD05-90 (push)
origin  https://github.com/MEN-Mikro-Elektronik/13MD05-90 (fetch)
origin  https://github.com/MEN-Mikro-Elektronik/13MD05-90 (push)
origin  https://github.com/MEN-Mikro-Elektronik/13MD05-90 (fetch)
origin  https://github.com/MEN-Mikro-Elektronik/13MD05-90 (push)
dpfeuffer@vm-suse:/opt/menlinux/HISTORY> cat 13M034-06_version.txt 13M066-06_version.txt 13Y004-06_version.txt
966a6ae6a2e7c4047edb861a1cda7e27a5003fba
966a6ae6a2e7c4047edb861a1cda7e27a5003fba
966a6ae6a2e7c4047edb861a1cda7e27a5003fba
```
If we stick to decision #61:
To Q1.
Possible solution, but more files.

To Q2.
I'm missing the date information, that is important for me.

3.
Could we change the _version.txt files from complete commit hash
e.g. ```966a6ae6a2e7c4047edb861a1cda7e27a5003fba```
To the demanded format, \<tag-numberOfCommits-abbrevCommit\>_\<date\>
e.g. ```13M099-06_02_15-0-g31531d1-dirty_2019-02-21```
or are the _version.txt files already evaluated by someone (tool, user)?

I think the new format would be also more useful for the customer. What do you think about it?

**Comment by KonradJPE** [comment]
> Yes, you are right, we decided to remove .git from the delivery package, but it is still included in the 13MD05-90_02_00 release archive files.

This is due the fact, that this issue was moved for release 02_01 - and now it is solved. 

> Therefore, I assumed, that the INSTALL script gets the git information with git from .git folder and I forgot decission #61 .

Creation of HISTORY dir is done automatically when .git directory is available, otherwise INSTALL script assumes, that correct HISTORY dir is already included in package and is copied into installation dir. I have created an issue some time ago that will remind us about HISTORY generation before release https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/88

> When I look into the /opt/menlinux/HISTORY/* files, I see that all submodules url and version points to 13MD05-90:

I'll check it

> Could we change the version.txt files from complete commit hash
> e.g. `966a6ae6a2e7c4047edb861a1cda7e27a5003fba`
> To the demanded format, <tag-numberOfCommits-abbrevCommit><date>
> e.g. 13M099-06_02_15-0-g31531d1-dirty_2019-02-21
> or are the _version.txt files already evaluated by someone (tool, user)?
> I think the new format would be also more useful for the customer. What do you think about it?

Yes, it will be more meaningful.
 I suppose this change will be easy to perform, and there should not be any dependencies with other sources.

**Comment by KonradJPE** [comment]
> > When I look into the /opt/menlinux/HISTORY/* files, I see that all submodules url and version points to 13MD05-90:
> 
> I'll check it

It is working correctly on sources from jpe-dev/master branch. Which version have you tested?
```
men@men:/opt/menlinux/HISTORY$ cat 13M034-06_url.txt 13M066-06_url.txt 13Y004-06_url.txt
origin	https://github.com/MEN-Mikro-Elektronik/13M034-06.git (fetch)
origin	https://github.com/MEN-Mikro-Elektronik/13M034-06.git (push)
origin	https://github.com/MEN-Mikro-Elektronik/13M066-06.git (fetch)
origin	https://github.com/MEN-Mikro-Elektronik/13M066-06.git (push)
origin	https://github.com/MEN-Mikro-Elektronik/13Y004-06.git (fetch)
origin	https://github.com/MEN-Mikro-Elektronik/13Y004-06.git (push)
```

**Comment by dpfeuffer** [comment]
I tested it with the last official release version 13MD05-90_02_00.
When I use current master branch 13MD05-90_02_00-3-g3a9cd49 I get the same output as you (ok).

**Comment by dpfeuffer** [comment]
> This is due the fact, that this issue was moved for release 02_01 - and now it is solved.

Ok, I understand now.

> Yes, it will be more meaningful.
>I suppose this change will be easy to perform, and there should not be any dependencies with other sources.

Ok, then please change it accordingly.

Thanks for your comments!

**Comment by KonradJPE** [comment]
@dpfeuffer I have additional question regarding $Id identifier. Example below.
```
static char* Ident( void )
{
    return( "Z61 - Z61 low-level driver: "
#ifdef MAC_BYTESWAP
    "swapped "
#else
    "non swapped "
#endif
    "$Id: z61_drv.c,v 1.3 2009/07/10 14:12:03 CRuff Exp $" );
}
```

Should i just replace all informations with IdentString?
```
static char* Ident( void )
{
    return( (char*) IdentString );
}
```

**Comment by dpfeuffer** [comment]
If we have just one or a few driver which provides the information of swapped or non swapped, then I would say we can skip this information.
If most drivers with swapped variants provide this distinct revision info, then we should solve it like this:

```
#ifdef MAC_BYTESWAP
    static const char IdentString[]=MENT_XSTR_SFX(MAK_REVISION, " (swapped)");
#else
    static const char IdentString[]=MENT_XSTR_SFX(MAK_REVISION, " (non swapped)");
#endif
```
SFX stands for suffix and the MENT_XSTR_SFX macro (tbd.) shall add the second argument to the MAK_REVISION.
Example: ```"13M099-06_02_15-0-g31531d1-dirty_2019-02-21 (swapped)"``` 
MENT_XSTR_SFX macro shall be defined in men_types.h

**Comment by KonradJPE** [comment]
> If we have just one or a few driver which provides the information of swapped or non swapped, then I would say we can skip this information.

There are 3 drivers that provides this swapped/non swapped information, so i suppose we can skip this. 


Should I also omit information about model? Please find example below - Only several modules use this information. 

```
static char* Ident(void)
{
	return ("Z17 - Z17 low level driver: $Id: z17_drv.c,v 1.15 2017/05/03 16:52:05 DPfeuffer Exp $"
			#ifdef Z17_MODEL_Z127
				" Z127 model"
			#else
				" Z34/Z37 model"
			#endif
			#ifdef Z127_NOIRQ
				" - no IRQs"
			#endif
			);
}
```

**Comment by dpfeuffer** [comment]
This model info may be important to know for our support team, when a customer run into problems. It's the same kind of additional information as with the swap/non-swap info. Because we may have in sum up to ten drivers with additional information, please try to use a new macro (MENT_XSTR_SFX) to add this info in brackets as I suggested.
For the z17 driver we have then four cases:
- " (Z127 model)"
- " (Z127 model, no IRQ)"
- " (Z34/Z37 model)"
- " (Z34/Z37 model, no IRQ)"

**Comment by KonradJPE** [comment]
Requirements R1-R7 should be now met.
Due to a large number of minor changes that have been done automatically by script, some tests should be performed.
 
After performing compilation test, and performing some simple tests (for R1-R7) requirements I will close the issue.

**Comment by mlassota** [comment]
Pull request https://github.com/MEN-Mikro-Elektronik/13MD05-90/pull/115 allowed all LL modules to display version info, but there are couple of modules that do not include this information. Would you like us to do the same for other modules?

**Comment by dpfeuffer** [comment]
Yes, see
>R6: The revision info of all used SW modules shall be updated

above.

**Comment by mlassota** [comment]
All requirements seem to be met.
