### ISSUE TITLE
compilation test for nodbg

### ISSUE THREAD

**Issue by dpfeuffer** [MEN-Mikro-Elektronik/13MD05-90#99]
In acceptance test for 13MD05-90_02_00_b2 the MDIS Build test case failed. See MEN inStep Customer\Milestone 13MD05-90_02_00\13MD05-90_SwDeliveryAcceptanceReport.docx MEN_13MD05-90_ST_0230.

I tried to determine if you performed your build test in 13MD05-90_02_00-System-TestReport (1).pdf JPE_13MD05-90_ST_xxxx_Compilation_xxx _Test with ALL_DBGS=nodbg or dbg but found no information about it.
Please do both tests: dbg and nodbg. Not any kernel/ALL_DBGS combination is necessary, it is sufficient to perform half of your current build tests with dbg and the others with nodbg.

**Comment by KonradJPE** [comment]
> I tried to determine if you performed your build test in 13MD05-90_02_00-System-TestReport (1).pdf JPE_13MD05-90_ST_xxxx_Compilation_xxx _Test with ALL_DBGS=nodbg or dbg but found no information about it.

Test was performed with dbg option. 
For the next release there will be tests for nodbg and dbg options.
